### ISSUE TITLE
installation of docker-compose and use of custom docker registry 

### ISSUE THREAD

**Issue by mike-ainsel** [lean-delivery/ansible-role-docker#3]
##### SUMMARY
It would be nice, if you could implement several additional features:
- possibility of docker-compose installation
- possibility to provide login credential for custom docker registry (such as nexus)

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME (for example)

**docker_registry:**
    registry_url: "nexus.localdomain.local:8083"
    registry_username: "local_user"
    registry_password: "local_user"
    registry_configuration_path: "$HOME/.docker/config.json" 

**docker_compose:**
   installed: true (default)
   compose_version: "1.23"

**Comment by vutkin** [comment]
Hi @mike-ainsel ,

please use `packages_additional` var in defaults:
```
packages_additional:
 - docker_compose
```
_Note_: Now it will install latest version.
